"""AI optimization engine — analyzes routing logs and suggests policy improvements.

Uses an LLM (typically a cheap model like flash) to analyze usage patterns
and generate concrete, actionable suggestions for policyflow.yaml changes.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from . import db
from .config import Config
from .models import ChatCompletionRequest, Message

logger = logging.getLogger(__name__)

_OPTIMIZER_PROMPT = """You are a policy optimization expert for PolicyFlow, an LLM routing middleware.
Analyze the usage data below and suggest concrete improvements to the YAML policy configuration.

## Current YAML Configuration
```yaml
{current_yaml}
```

## Period Statistics
Total requests: {total_requests}
Total cost: ¥{total_cost:.2f}

## Per-Policy Stats
{policy_stats_table}

## Unmatched Request Clusters
These requests hit the default policy (no specific match). Each cluster represents
a group of similar prompts that could become a new policy.
{unmatched_clusters}

## Cascade Anomalies
Failed cascade attempts with validation reasons (when available).
{cascade_anomalies}

## Instructions
Analyze the data and generate up to {max_suggestions} optimization suggestions.
Each suggestion should be specific and actionable. For new policies, include a
complete YAML snippet.

Return your response as a JSON array:
```json
[
  {{
    "kind": "new_policy|policy_split|threshold_adjustment|escalation_change",
    "title": "Short title in Chinese",
    "description": "Why this change helps, with numbers",
    "yaml_snippet": "...",
    "estimated_savings_monthly": 0.0,
    "risk": "low|medium|high"
  }}
]
```

IMPORTANT: Return ONLY the JSON array, no other text."""


@dataclass
class OptimizationSuggestion:
    """A single optimization suggestion generated by the AI engine."""

    kind: str  # new_policy | policy_split | threshold_adjustment | escalation_change
    title: str
    description: str
    yaml_snippet: str = ""
    estimated_savings_monthly: float = 0.0
    risk: str = "low"


@dataclass
class OptimizationResult:
    """Complete optimization analysis result."""

    suggestions: list[OptimizationSuggestion] = field(default_factory=list)
    total_estimated_savings: float = 0.0
    period: str = ""
    raw_response: str = ""


async def generate_optimizations(
    config: Config,
    proxy,  # UpstreamProxy (avoid circular import)
    days: int = 30,
    max_suggestions: int = 5,
) -> OptimizationResult:
    """Analyze routing logs and generate policy optimization suggestions.

    Args:
        config: PolicyFlow Config instance
        proxy: UpstreamProxy instance (for calling the LLM)
        days: Number of days of history to analyze
        max_suggestions: Maximum number of suggestions to generate

    Returns:
        OptimizationResult with actionable suggestions.
    """
    optimizer_cfg = config.optimizer_data
    model = optimizer_cfg.get("model", "deepseek-v4-flash")
    if not optimizer_cfg.get("enabled", True):
        return OptimizationResult(period=f"{days}d")

    # ── Collect data from DB ─────────────────────────────────
    summary = db.query_summary(days)
    policy_stats = db.query_policy_stats(days)
    unmatched = db.query_unmatched_prompts(days, limit=8)
    anomalies = db.query_cascade_anomalies(days, limit=20)

    # ── Format policy stats table ────────────────────────────
    stats_lines = []
    for ps in policy_stats:
        stats_lines.append(
            f"  {ps['name']}: {ps['hits']} requests, ¥{ps['total_cost']:.2f}, "
            f"avg similarity {ps['avg_similarity']}, cascade {ps['cascade_pct']}%"
        )
    policy_table = "\n".join(stats_lines) if stats_lines else "  (no data)"

    # ── Format unmatched clusters ────────────────────────────
    unmatched_lines = []
    for u in unmatched:
        preview = u.get("prompt_preview", "")[:80]
        unmatched_lines.append(
            f"  [{u['cnt']} requests] prompt_hash={u['prompt_hash']}: \"{preview}...\""
        )
    unmatched_text = "\n".join(unmatched_lines) if unmatched_lines else "  (none)"

    # ── Format cascade anomalies ─────────────────────────────
    anomaly_lines = []
    for a in anomalies[:10]:
        reason = a.get("judge_reason", "unknown")[:100]
        anomaly_lines.append(
            f"  policy={a['policy_name']} model={a['routed_model']}: {reason}"
        )
    anomaly_text = "\n".join(anomaly_lines) if anomaly_lines else "  (none)"

    # ── Read current YAML ────────────────────────────────────
    try:
        with open(config.path, encoding="utf-8") as f:
            current_yaml = f.read()
    except Exception as exc:
        logger.warning("Could not read policyflow.yaml: %s — optimizer will run without config context", exc)
        current_yaml = "# (could not read policyflow.yaml)"

    # ── Construct prompt ─────────────────────────────────────
    prompt = _OPTIMIZER_PROMPT.format(
        current_yaml=current_yaml,
        total_requests=summary["total_requests"],
        total_cost=summary["total_cost"],
        policy_stats_table=policy_table,
        unmatched_clusters=unmatched_text,
        cascade_anomalies=anomaly_text,
        max_suggestions=max_suggestions,
    )

    # ── Call LLM ─────────────────────────────────────────────
    request = ChatCompletionRequest(
        model=model,
        messages=[Message(role="user", content=prompt)],
    )

    try:
        response, _ = await proxy.chat_completion_with_fallback(request)
        raw = response.choices[0].message.content or ""
    except Exception as exc:
        logger.warning("Optimizer LLM call failed: %s", exc)
        return OptimizationResult(
            period=f"{days}d",
            raw_response=str(exc),
        )

    # ── Parse response ───────────────────────────────────────
    suggestions = _parse_suggestions(raw)
    total_savings = sum(s.estimated_savings_monthly for s in suggestions)

    return OptimizationResult(
        suggestions=suggestions,
        total_estimated_savings=round(total_savings, 2),
        period=f"{days}d",
        raw_response=raw,
    )


def _parse_suggestions(raw: str) -> list[OptimizationSuggestion]:
    """Parse LLM response into a list of OptimizationSuggestion."""
    import json

    # Extract JSON from response (may be wrapped in markdown code block)
    text = raw.strip()
    # Try to find JSON array in code blocks
    import re
    match = re.search(r"```(?:json)?\s*(\[[\s\S]*?\])\s*```", text)
    if match:
        text = match.group(1)
    # Try to find bare JSON array
    if not text.startswith("["):
        match = re.search(r"\[[\s\S]*\]", text)
        if match:
            text = match.group(0)

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        logger.warning("Failed to parse optimizer response as JSON, raw=%s", raw[:500])
        return []

    suggestions = []
    for item in data:
        if not isinstance(item, dict):
            continue
        suggestions.append(OptimizationSuggestion(
            kind=item.get("kind", "unknown"),
            title=item.get("title", ""),
            description=item.get("description", ""),
            yaml_snippet=item.get("yaml_snippet", ""),
            estimated_savings_monthly=float(item.get("estimated_savings_monthly", 0) or 0),
            risk=item.get("risk", "low"),
        ))
    return suggestions
